package com.ppp.prm.portal.shared.dto;
// Generated May 9, 2012 10:13:17 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * MNews generated by hbm2java
 */
public class MNews  implements java.io.Serializable {


     private String id;
     private MTypeMain MTypeMain;
     private MUser MUser;
     private MKeyword MKeyword;
     private int rid;
     private Date created;
     private Date updated;
     private String descr;
     private String type;
    //  private Set MCommentses = new HashSet(0);

    public MNews() {
    }

    
    public MNews(String id, int rid, Date created, Date updated,MTypeMain MTypeMain,
    		 MUser MUser,MKeyword MKeyword, String descr,String type)
    		{
        	this.id = id;
        	this.rid = rid;
        	this.created = created;
        	this.updated = updated;
        	this.MTypeMain = MTypeMain;
        	this.MUser = MUser;
        	this.MKeyword = MKeyword;
        	this.descr = descr;
        	this.type = type;
        }
	
    public MNews(String id, int rid, Date created, Date updated) {
        this.id = id;
        this.rid = rid;
        this.created = created;
        this.updated = updated;
    }
/*    public MNews(String id, MTypeMain MTypeMain, MUser MUser, MKeyword MKeyword, int rid, Date created, Date updated, String descr, String type, Set MCommentses) {
       this.id = id;
       this.MTypeMain = MTypeMain;
       this.MUser = MUser;
       this.MKeyword = MKeyword;
       this.rid = rid;
       this.created = created;
       this.updated = updated;
       this.descr = descr;
       this.type = type;
       this.MCommentses = MCommentses;
    }*/
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public MTypeMain getMTypeMain() {
        return this.MTypeMain;
    }
    
    public void setMTypeMain(MTypeMain MTypeMain) {
        this.MTypeMain = MTypeMain;
    }
    public MUser getMUser() {
        return this.MUser;
    }
    
    public void setMUser(MUser MUser) {
        this.MUser = MUser;
    }
    public MKeyword getMKeyword() {
        return this.MKeyword;
    }
    
    public void setMKeyword(MKeyword MKeyword) {
        this.MKeyword = MKeyword;
    }
    public int getRid() {
        return this.rid;
    }
    
    public void setRid(int rid) {
        this.rid = rid;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    
    public void setItem(String descr) {
        this.descr = descr;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
  /*  public Set getMCommentses() {
        return this.MCommentses;
    }
    
    public void setMCommentses(Set MCommentses) {
        this.MCommentses = MCommentses;
    }*/




}


