package com.ppp.prm.portal.shared.dto;
// Generated May 9, 2012 10:13:17 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * MTypeMain generated by hbm2java
 */
public class MTypeMain  implements java.io.Serializable {


     private String id;
     private int rid;
     private String name;
     private Date created;
     private Date updated;
    /* private Set MMKeyword = new HashSet(0);
     private Set MNewses = new HashSet(0);*/

    public MTypeMain() {
    }

	
    public MTypeMain(String id, int rid, String name, Date created, Date updated) {
        this.id = id;
        this.rid = rid;
        this.name = name;
        this.created = created;
        this.updated = updated;
    }
  
    
  /*   public MTypeMain(String id, int rid, String name, Date created, Date updated, Set MMKeyword, Set MNewses) {
  
       this.id = id;
       this.rid = rid;
       this.name = name;
       this.created = created;
       this.updated = updated;
       this.MMKeyword = MMKeyword;
       this.MNewses = MNewses;
    }*/
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public int getRid() {
        return this.rid;
    }
    
    public void setRid(int rid) {
        this.rid = rid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
/*    public Set getMMKeyword() {
        return this.MMKeyword;
    }
    
    public void setMMKeyword(Set MMKeyword) {
        this.MMKeyword = MMKeyword;
    }
    public Set getMNewses() {
        return this.MNewses;
    }
    
    public void setMNewses(Set MNewses) {
        this.MNewses = MNewses;
    }*/




}


