package com.ppp.prm.portal.shared.dto;
// Generated May 9, 2012 10:13:17 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * MUser generated by hbm2java
 */
public class MUser  implements java.io.Serializable {


     private String id;
     private int rid;
     private Date created;
     private Date updated;
     private String login;
     private String passwd;
     private String fstName;
     private String lastName;
    /* private Set MCommentses = new HashSet(0);
     private Set MUserRelsForSecUserKey = new HashSet(0);
     private Set MNewses = new HashSet(0);
     private Set MUserRelsForPriUserKey = new HashSet(0);
*/
    public MUser() {
    }

	
    public MUser(String id, int rid, Date created, Date updated) {
        this.id = id;
        this.rid = rid;
        this.created = created;
        this.updated = updated;
    }
    public MUser(String id, int rid, Date created, Date updated, String login, String passwd, String fstName, String lastName) {
       this.id = id;
       this.rid = rid;
       this.created = created;
       this.updated = updated;
       this.login = login;
       this.passwd = passwd;
       this.fstName = fstName;
       this.lastName = lastName;
     
      /* this.MCommentses = MCommentses;
       this.MUserRelsForSecUserKey = MUserRelsForSecUserKey;
       this.MNewses = MNewses;
       this.MUserRelsForPriUserKey = MUserRelsForPriUserKey;*/
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public int getRid() {
        return this.rid;
    }
    
    public void setRid(int rid) {
        this.rid = rid;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public String getFstName() {
        return this.fstName;
    }
    
    public void setFstName(String fstName) {
        this.fstName = fstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
   /* public Set getMCommentses() {
        return this.MCommentses;
    }
    
    public void setMCommentses(Set MCommentses) {
        this.MCommentses = MCommentses;
    }
    public Set getMUserRelsForSecUserKey() {
        return this.MUserRelsForSecUserKey;
    }
    
    public void setMUserRelsForSecUserKey(Set MUserRelsForSecUserKey) {
        this.MUserRelsForSecUserKey = MUserRelsForSecUserKey;
    }
    public Set getMNewses() {
        return this.MNewses;
    }
    
    public void setMNewses(Set MNewses) {
        this.MNewses = MNewses;
    }
    public Set getMUserRelsForPriUserKey() {
        return this.MUserRelsForPriUserKey;
    }
    
    public void setMUserRelsForPriUserKey(Set MUserRelsForPriUserKey) {
        this.MUserRelsForPriUserKey = MUserRelsForPriUserKey;
    }

*/


}


