package com.ppp.prm.portal.shared.dto;
// Generated May 9, 2012 10:13:17 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * ALstVal generated by hbm2java
 */
public class ALstVal  implements java.io.Serializable {


     private int id;
     private Date created;
     private Date updated;
     private String rid;
     private String name;
     private String type;
     private String subType;
     private String description;
     private Integer parentId;

    public ALstVal() {
    }

	
    public ALstVal(int id, Date created, Date updated) {
        this.id = id;
        this.created = created;
        this.updated = updated;
    }
    public ALstVal(int id, Date created, Date updated, String rid, String name, String type, String subType, String description, Integer parentId) {
       this.id = id;
       this.created = created;
       this.updated = updated;
       this.rid = rid;
       this.name = name;
       this.type = type;
       this.subType = subType;
       this.description = description;
       this.parentId = parentId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public String getRid() {
        return this.rid;
    }
    
    public void setRid(String rid) {
        this.rid = rid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getSubType() {
        return this.subType;
    }
    
    public void setSubType(String subType) {
        this.subType = subType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description=description ;
    }
    
    public void setItemiption(String description) {
        this.description = description;
    }
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }




}


