package com.ppp.prm.portal.shared.dto;
// Generated May 9, 2012 10:13:17 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * MComments generated by hbm2java
 */
public class MComments  implements java.io.Serializable {


     private Integer id;
     private MNews MNews;
     private MUser MUser;
     private int rid;
     private String descr;
     private Date created;
     private Date updated;

    public MComments(String ID, String COMMENT) {
		// TODO Auto-generated constructor stub
    	// id = "";
    	descr=COMMENT;
	}


	


	public  MComments() {
    }

	
    public void MComments(int rid, Date created, Date updated) {
        this.rid = rid;
        this.created = created;
        this.updated = updated;
    }
    public void MComments(MNews MNews, MUser MUser, int rid, String descr, Date created, Date updated) {
       this.MNews = MNews;
       this.MUser = MUser;
       this.rid = rid;
       this.descr = descr;
       this.created = created;
       this.updated = updated;
    }
   
    public  Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MNews getMNews() {
        return this.MNews;
    }
    
    public void setMNews(MNews MNews) {
        this.MNews = MNews;
    }
    public MUser getMUser() {
        return this.MUser;
    }
    
    public void setMUser(MUser MUser) {
        this.MUser = MUser;
    }
    public int getRid() {
        return this.rid;
    }
    
    public void setRid(int rid) {
        this.rid = rid;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    
    public void setItem(String descr) {
        this.descr = descr;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }




}


